FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-20

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#  && apt-get -y install --no-install-recommends

RUN su node -c "npm install -g pnpm@8.15.2"